In [128]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [129]:
df=pd.read_csv("data.csv")

In [130]:
df.head()

,price,bedrooms,sqft_living,sqft_lot,floors,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city
0,313000.0,3,1340,7912,1.5,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline
1,2384000.0,5,3650,9050,2.0,4,5,3370,280,1921,0,709 W Blaine St,Seattle
2,342000.0,3,1930,11947,1.0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent
3,420000.0,3,2000,8030,1.0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue
4,550000.0,4,1940,10500,1.0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond

In [131]:
df.drop("street",inplace=True,axis=1)

In [132]:
df.drop("city",inplace=True,axis=1)

In [133]:
df.columns

Index(['price', 'bedrooms', 'sqft_living', 'sqft_lot', 'floors', 'view',
       'condition', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated'],
      dtype='object')

In [134]:
df.isnull().sum()

price            0
bedrooms         0
sqft_living      0
sqft_lot         0
floors           0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
dtype: int64

In [135]:
df["bedrooms"].value_counts()

bedrooms
3    2032
4    1531
2     566
5     353
6      61
1      38
7      14
8       2
0       2
9       1
Name: count, dtype: int64

In [136]:
df["floors"].value_counts()

floors
1.0    2174
2.0    1811
1.5     444
3.0     128
2.5      41
3.5       2
Name: count, dtype: int64

In [137]:
df["yr_built"].value_counts()

yr_built
2006    111
2005    104
2007     93
2004     92
1978     90
       ...
1915      6
1935      6
1933      5
1934      4
1936      3
Name: count, Length: 115, dtype: int64

In [138]:
x=df.drop(["price"],axis=1)

In [139]:
x.columns

Index(['bedrooms', 'sqft_living', 'sqft_lot', 'floors', 'view', 'condition',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated'],
      dtype='object')

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   int64
 2   sqft_living    4600 non-null   int64
 3   sqft_lot       4600 non-null   int64
 4   floors         4600 non-null   float64
 5   view           4600 non-null   int64
 6   condition      4600 non-null   int64
 7   sqft_above     4600 non-null   int64
 8   sqft_basement  4600 non-null   int64
 9   yr_built       4600 non-null   int64
 10  yr_renovated   4600 non-null   int64
dtypes: float64(2), int64(9)
memory usage: 395.4 KB

In [141]:
y=df["price"]

In [142]:
df.shape

(4600, 11)

In [143]:
cat_feature=[feature for feature in df.columns if df[feature].dtype=='O']

In [144]:
cat_feature

[]

In [145]:
num_feature=[feature for feature in df.columns if df[feature].dtypes!='O']

In [146]:
num_feature

['price',
 'bedrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'view',
 'condition',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated']

Train test split

In [147]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [148]:
x_train.shape

(3450, 10)

In [149]:
x_train

,bedrooms,sqft_living,sqft_lot,floors,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
2095,3,1860,7963,1.0,0,3,1200,660,1963,2008
1173,2,1070,5824,1.0,2,5,1070,0,1949,0
1954,4,1920,10403,1.0,0,3,1370,550,1959,1989
256,3,1580,9147,1.0,1,4,1210,370,1967,0
3341,3,1640,8400,1.0,0,3,1180,460,1968,1997
...,...,...,...,...,...,...,...,...,...,...
4426,3,1180,5002,1.5,0,3,1180,0,1946,0
466,4,2520,6000,1.0,0,3,1400,1120,1921,2007
3092,3,1150,8145,1.0,0,4,990,160,1932,1958
3772,2,910,2002,1.5,0,3,910,0,1900,2005
860,2,1490,3825,1.0,0,3,860,630,1929,0

In [150]:
y_train

2095    288350.000000
1173    319950.000000
1954    210000.000000
256     515000.000000
3341    245700.000000
            ...
4426    282508.888889
466     875000.000000
3092    290000.000000
3772    600000.000000
860     475000.000000
Name: price, Length: 3450, dtype: float64

In [151]:
x_test.shape

(1150, 10)

Column Transformer

In [152]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
cat_features=x.select_dtypes(include="object").columns
num_features=x.select_dtypes(exclude="object").columns

from sklearn.compose import ColumnTransformer
scaler=StandardScaler()


preprocessor=ColumnTransformer(
    [
        
        ("StandardScaler",scaler,num_features)
    ]
)

In [153]:
preprocessor

ColumnTransformer(transformers=[('StandardScaler', StandardScaler(),
                                 Index(['bedrooms', 'sqft_living', 'sqft_lot', 'floors', 'view', 'condition',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated'],
      dtype='object'))])

In [154]:
x_train=preprocessor.fit_transform(x_train)

In [155]:
x_test=preprocessor.transform(x_test)

In [156]:
from sklearn.svm import SVR
model=SVR()

In [157]:
model.fit(x_train,y_train)

SVR()

In [158]:
y_pred=model.predict(x_test)

In [159]:
y_pred

array([462933.37092236, 463049.38598376, 463182.16544497, ...,
       462793.46407544, 463069.48945226, 463155.63184108])

In [160]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [161]:
print("The r2 score is " , r2_score(y_test,y_pred))
print("The mean absolute error  is " , mean_absolute_error(y_test,y_pred))

The r2 score is  -0.01457721572408932
The mean absolute error  is  258130.29187170143

Hyper parameter tuning

In [162]:
from sklearn.model_selection import GridSearchCV
param_grid={
    'C':[0.1,1,10,100,1000],
    'gamma':[1,0.1,0.01,0.001],
    'kernel':['rbf']
}

In [163]:
grid=GridSearchCV(SVR(),param_grid=param_grid,verbose=3,refit=True)

In [166]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.046 total time=   0.5s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.048 total time=   0.6s
[CV 3/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.040 total time=   0.6s
[CV 4/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.057 total time=   0.5s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.046 total time=   0.5s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.048 total time=   0.6s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.040 total time=   0.6s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.057 total time=   0.7s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.046 total time=   0.5s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.048 total time=   0.6s
[CV 3/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.040 total time=   0.6s
[CV 4/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.057 total time=   0.6s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.048 total time=   0.6s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.040 total time=   0.6s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.057 total time=   0.6s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 1/5] END .........C=1, gamma=1, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 2/5] END .........C=1, gamma=1, kernel=rbf;, score=-0.048 total time=   0.5s
[CV 3/5] END .........C=1, gamma=1, kernel=rbf;, score=-0.040 total time=   0.6s
[CV 4/5] END .........C=1, gamma=1, kernel=rbf;, score=-0.057 total time=   0.6s
[CV 5/5] END .........C=1, gamma=1, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 1/5] END .......C=1, gamma=0.1, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 2/5] END .......C=1, gamma=0.1, kernel=rbf;, score=-0.048 total time=   0.6s
[CV 3/5] END .......C=1, gamma=0.1, kernel=rbf;, score=-0.040 total time=   0.6s
[CV 4/5] END .......C=1, gamma=0.1, kernel=rbf;, score=-0.056 total time=   0.6s
[CV 5/5] END .......C=1, gamma=0.1, kernel=rbf;, score=-0.045 total time=   0.6s
[CV 1/5] END ......C=1, gamma=0.01, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 2/5] END ......C=1, gamma=0.01, kernel=rbf;, score=-0.048 total time=   0.8s
[CV 3/5] END ......C=1, gamma=0.01, kernel=rbf;, score=-0.040 total time=   0.7s
[CV 4/5] END ......C=1, gamma=0.01, kernel=rbf;, score=-0.056 total time=   0.6s
[CV 5/5] END ......C=1, gamma=0.01, kernel=rbf;, score=-0.045 total time=   0.8s
[CV 1/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.046 total time=   0.8s
[CV 2/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.048 total time=   0.9s
[CV 3/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.040 total time=   0.8s
[CV 4/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.057 total time=   0.7s
[CV 5/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.046 total time=   0.7s
[CV 1/5] END ........C=10, gamma=1, kernel=rbf;, score=-0.046 total time=   0.7s
[CV 2/5] END ........C=10, gamma=1, kernel=rbf;, score=-0.048 total time=   0.8s
[CV 3/5] END ........C=10, gamma=1, kernel=rbf;, score=-0.040 total time=   0.7s
[CV 4/5] END ........C=10, gamma=1, kernel=rbf;, score=-0.056 total time=   0.7s
[CV 5/5] END ........C=10, gamma=1, kernel=rbf;, score=-0.045 total time=   0.8s
[CV 1/5] END ......C=10, gamma=0.1, kernel=rbf;, score=-0.042 total time=   0.7s
[CV 2/5] END ......C=10, gamma=0.1, kernel=rbf;, score=-0.045 total time=   0.7s
[CV 3/5] END ......C=10, gamma=0.1, kernel=rbf;, score=-0.037 total time=   0.7s
[CV 4/5] END ......C=10, gamma=0.1, kernel=rbf;, score=-0.053 total time=   0.6s
[CV 5/5] END ......C=10, gamma=0.1, kernel=rbf;, score=-0.041 total time=   0.7s
[CV 1/5] END .....C=10, gamma=0.01, kernel=rbf;, score=-0.044 total time=   0.6s
[CV 2/5] END .....C=10, gamma=0.01, kernel=rbf;, score=-0.046 total time=   0.7s
[CV 3/5] END .....C=10, gamma=0.01, kernel=rbf;, score=-0.039 total time=   0.7s
[CV 4/5] END .....C=10, gamma=0.01, kernel=rbf;, score=-0.055 total time=   0.7s
[CV 5/5] END .....C=10, gamma=0.01, kernel=rbf;, score=-0.043 total time=   0.7s
[CV 1/5] END ....C=10, gamma=0.001, kernel=rbf;, score=-0.046 total time=   0.6s
[CV 2/5] END ....C=10, gamma=0.001, kernel=rbf;, score=-0.048 total time=   0.8s
[CV 3/5] END ....C=10, gamma=0.001, kernel=rbf;, score=-0.040 total time=   0.7s
[CV 4/5] END ....C=10, gamma=0.001, kernel=rbf;, score=-0.056 total time=   0.6s
[CV 5/5] END ....C=10, gamma=0.001, kernel=rbf;, score=-0.045 total time=   0.8s
[CV 1/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.041 total time=   0.7s
[CV 2/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.044 total time=   0.8s
[CV 3/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.037 total time=   0.7s
[CV 4/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.053 total time=   0.6s
[CV 5/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.040 total time=   0.8s
[CV 1/5] END .....C=100, gamma=0.1, kernel=rbf;, score=-0.005 total time=   0.7s
[CV 2/5] END .....C=100, gamma=0.1, kernel=rbf;, score=-0.017 total time=   0.7s
[CV 3/5] END .....C=100, gamma=0.1, kernel=rbf;, score=-0.005 total time=   0.7s
[CV 4/5] END .....C=100, gamma=0.1, kernel=rbf;, score=-0.027 total time=   0.6s
[CV 5/5] END .....C=100, gamma=0.1, kernel=rbf;, score=-0.004 total time=   0.8s
[CV 1/5] END ....C=100, gamma=0.01, kernel=rbf;, score=-0.023 total time=   0.7s
[CV 2/5] END ....C=100, gamma=0.01, kernel=rbf;, score=-0.029 total time=   0.7s
[CV 3/5] END ....C=100, gamma=0.01, kernel=rbf;, score=-0.020 total time=   0.8s
[CV 4/5] END ....C=100, gamma=0.01, kernel=rbf;, score=-0.040 total time=   0.7s
[CV 5/5] END ....C=100, gamma=0.01, kernel=rbf;, score=-0.024 total time=   0.7s
[CV 1/5] END ...C=100, gamma=0.001, kernel=rbf;, score=-0.043 total time=   0.7s
[CV 2/5] END ...C=100, gamma=0.001, kernel=rbf;, score=-0.045 total time=   0.8s
[CV 3/5] END ...C=100, gamma=0.001, kernel=rbf;, score=-0.038 total time=   0.8s
[CV 4/5] END ...C=100, gamma=0.001, kernel=rbf;, score=-0.054 total time=   0.6s
[CV 5/5] END ...C=100, gamma=0.001, kernel=rbf;, score=-0.043 total time=   0.8s
[CV 1/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.000 total time=   0.7s
[CV 2/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.014 total time=   0.7s
[CV 3/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.001 total time=   0.8s
[CV 4/5] END ......C=1000, gamma=1, kernel=rbf;, score=-0.027 total time=   0.7s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.004 total time=   0.7s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.183 total time=   0.7s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.111 total time=   0.7s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.145 total time=   0.8s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.095 total time=   0.7s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.176 total time=   0.8s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.131 total time=   0.7s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.087 total time=   0.6s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.113 total time=   0.7s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.068 total time=   0.7s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.114 total time=   0.7s
[CV 1/5] END ..C=1000, gamma=0.001, kernel=rbf;, score=-0.017 total time=   0.9s
[CV 2/5] END ..C=1000, gamma=0.001, kernel=rbf;, score=-0.021 total time=   0.9s
[CV 3/5] END ..C=1000, gamma=0.001, kernel=rbf;, score=-0.013 total time=   0.8s
[CV 4/5] END ..C=1000, gamma=0.001, kernel=rbf;, score=-0.033 total time=   0.7s
[CV 5/5] END ..C=1000, gamma=0.001, kernel=rbf;, score=-0.018 total time=   0.8s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001], 'kernel': ['rbf']},
             verbose=3)

In [167]:
grid.best_params_

{'C': 1000, 'gamma': 0.1, 'kernel': 'rbf'}

In [168]:
grid.best_score_

0.1421873315394599

In [169]:
y_pred=grid.predict(x_test)